version: '3.8'

services:
  ingest-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chakal-ingest
    depends_on:
      - clickhouse
    environment:
      - TIKTOK_HOST=${TIKTOK_HOST:-mockhost}
      - CLICKHOUSE_CONN=Host=clickhouse;Port=8123;Database=chakal;User=default;Password=Chakal123!
      - LOG_LEVEL=${LOG_LEVEL:-Debug}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - MINIO_STORAGE_AVAILABLE=${MINIO_STORAGE_AVAILABLE:-true}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://192.168.1.230:9100}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-vFpdN5CJGjY5o0jPKVww}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-5KpII0ID5oOqFOmSR8G6rd7HJJNBFb9eD1Xb3dTB}
      - S3_BUCKET=${S3_BUCKET:-dev-chakal-raw}
    ports:
      - "5000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: chakal-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./sql/chakal_clickhouse.sql:/docker-entrypoint-initdb.d/chakal_clickhouse.sql
      - ./init-clickhouse.sh:/docker-entrypoint-initdb.d/init-clickhouse.sh
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=Chakal123!
      - CLICKHOUSE_DB=chakal
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      
volumes:
  clickhouse-data: 