version: '3.8'

services:
  ingest-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chakal-ingest
    depends_on:
      - clickhouse
    environment:
      - TIKTOK_HOST=${TIKTOK_HOST:-mockhost}
      - CLICKHOUSE_CONN=Host=clickhouse;Port=8123;Database=chakal;User=default;Password=Chakal123!
      - LOG_LEVEL=${LOG_LEVEL:-Debug}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    ports:
      - "5000:80"
    restart: unless-stopped
    
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: chakal-clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=Chakal123!
      - CLICKHOUSE_DB=chakal
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
      
volumes:
  clickhouse-data: 